import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { formatBillingJs, formatConsoleLine } from '../src/format.js';

// ── formatBillingJs ──────────────────────────────

describe('formatBillingJs', () => {
  it('wraps data in window.BILLING assignment', () => {
    const data = { timestamp: '2026-08-14T00:00:00.000Z', providers: {} };
    const output = formatBillingJs(data);
    assert.ok(output.startsWith('// Auto-generated by amster dump'));
    assert.ok(output.includes('window.BILLING = '));
    assert.ok(output.endsWith(';\n'));
  });

  it('includes timestamp in comment', () => {
    const data = { timestamp: '2026-08-14T12:00:00.000Z', providers: {} };
    const output = formatBillingJs(data);
    assert.ok(output.includes('2026-08-14T12:00:00.000Z'));
  });

  it('produces valid JSON inside assignment', () => {
    const data = {
      timestamp: '2026-08-14T00:00:00.000Z',
      providers: { deepseek: { detected: true, balance: 42.5 } },
    };
    const output = formatBillingJs(data);
    const jsonStr = output.split('window.BILLING = ')[1].replace(/;\s*$/, '');
    const parsed = JSON.parse(jsonStr);
    assert.equal(parsed.providers.deepseek.balance, 42.5);
  });
});

// ── formatConsoleLine ────────────────────────────

describe('formatConsoleLine', () => {
  it('shows not configured', () => {
    const line = formatConsoleLine('openai', { detected: false });
    assert.ok(line.includes('not configured'));
    assert.ok(line.includes('openai'));
  });

  it('shows balance with currency', () => {
    const line = formatConsoleLine('deepseek', { detected: true, balance: 42.5, currency: 'CNY' });
    assert.ok(line.includes('*'));
    assert.ok(line.includes('CNY 42.50'));
    assert.ok(line.includes('remaining'));
  });

  it('shows usage with limit', () => {
    const line = formatConsoleLine('usagetest', { detected: true, usage: 3.14, limit: 50 });
    assert.ok(line.includes('$3.14 used'));
    assert.ok(line.includes('50.00 limit'));
  });

  it('shows usage without limit', () => {
    const line = formatConsoleLine('usagetest', { detected: true, usage: 1.0, limit: null });
    assert.ok(line.includes('$1.00 used'));
    assert.ok(line.includes('no limit'));
  });

  it('shows username', () => {
    const line = formatConsoleLine('huggingface', { detected: true, username: 'eve' });
    assert.ok(line.includes('*'));
    assert.ok(line.includes('eve'));
  });

  it('shows model count', () => {
    const line = formatConsoleLine('openai', { detected: true, models: 10, verified: true });
    assert.ok(line.includes('10 models'));
  });

  it('shows key verified', () => {
    const line = formatConsoleLine('openai', { detected: true, verified: true });
    assert.ok(line.includes('*'));
    assert.ok(line.includes('key verified'));
  });

  it('shows error', () => {
    const line = formatConsoleLine('groq', { detected: true, error: 'HTTP 401' });
    assert.ok(line.includes('!'));
    assert.ok(line.includes('HTTP 401'));
  });

  it('shows unknown for unrecognized data', () => {
    const line = formatConsoleLine('weird', { detected: true });
    assert.ok(line.includes('unknown'));
  });
});
