import { describe, it, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { createApp } from '../src/server.js';

function mockFetch(body, status = 200) {
  return async () => ({ ok: status >= 200 && status < 300, status, json: async () => body });
}

async function listen(app) {
  return new Promise((resolve) => {
    const server = app.listen(0, () => resolve(server));
  });
}

function baseUrl(server) {
  const addr = server.address();
  return `http://127.0.0.1:${addr.port}`;
}

describe('server', () => {
  let server;
  let base;

  before(async () => {
    server = await listen(createApp({ env: {}, fetchFn: mockFetch({}), loadEnv: false }));
    base = baseUrl(server);
  });

  after(() => server.close());

  it('serves index.html at /', async () => {
    const res = await fetch(`${base}/`);
    assert.equal(res.status, 200);
    const text = await res.text();
    assert.ok(text.includes('Amsterdam Console'));
  });

  it('serves index.html at /index.html', async () => {
    const res = await fetch(`${base}/index.html`);
    assert.equal(res.status, 200);
  });

  it('returns 404 for unknown paths', async () => {
    const res = await fetch(`${base}/nope`);
    assert.equal(res.status, 404);
  });

  it('returns billing JSON at /api/billing', async () => {
    const res = await fetch(`${base}/api/billing`);
    assert.equal(res.status, 200);
    const data = await res.json();
    assert.ok(data.timestamp);
    assert.ok(data.providers);
    for (const p of Object.values(data.providers)) {
      assert.equal(p.detected, false);
    }
  });

  it('serves data/billing.js as generated JS', async () => {
    const res = await fetch(`${base}/data/billing.js`);
    assert.equal(res.status, 200);
    const text = await res.text();
    assert.ok(text.startsWith('// Auto-generated by amster dump'));
    assert.ok(text.includes('window.BILLING = '));
  });
});

describe('server caching', () => {
  it('caches /api/billing within TTL', async () => {
    let calls = 0;
    const countingFetch = async () => {
      calls++;
      return {
        ok: true,
        json: async () => ({ balance_infos: [{ currency: 'CNY', total_balance: '10' }], is_available: true }),
      };
    };
    const env = { DEEPSEEK_API_KEY: 'sk-test' };
    const app = await listen(createApp({ env, fetchFn: countingFetch, loadEnv: false }));
    const base = baseUrl(app);

    await fetch(`${base}/api/billing`);
    await fetch(`${base}/api/billing`);
    assert.equal(calls, 1);

    app.close();
  });

  it('bypasses cache with ?fresh=1', async () => {
    let calls = 0;
    const countingFetch = async () => {
      calls++;
      return {
        ok: true,
        json: async () => ({ balance_infos: [{ currency: 'CNY', total_balance: '10' }], is_available: true }),
      };
    };
    const env = { DEEPSEEK_API_KEY: 'sk-test' };
    const app = await listen(createApp({ env, fetchFn: countingFetch, loadEnv: false }));
    const base = baseUrl(app);

    await fetch(`${base}/api/billing`);
    await fetch(`${base}/api/billing?fresh=1`);
    assert.equal(calls, 2);

    app.close();
  });
});
