import { describe, it, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { createApp } from '../src/server.js';

function mockFetch(body, status = 200) {
  return async () => ({ ok: status >= 200 && status < 300, status, json: async () => body });
}

async function listen(app) {
  return new Promise((resolve) => {
    const server = app.listen(0, () => resolve(server));
  });
}

function baseUrl(server) {
  const addr = server.address();
  return `http://127.0.0.1:${addr.port}`;
}

describe('server', () => {
  let server;
  let base;

  before(async () => {
    server = await listen(createApp({ env: {}, fetchFn: mockFetch({}), loadEnv: false }));
    base = baseUrl(server);
  });

  after(() => server.close());

  it('serves index.html at /', async () => {
    const res = await fetch(`${base}/`);
    assert.equal(res.status, 200);
    const text = await res.text();
    assert.ok(text.includes('Amsterdam Console'));
  });

  it('serves index.html at /index.html', async () => {
    const res = await fetch(`${base}/index.html`);
    assert.equal(res.status, 200);
  });

  it('returns 404 for unknown paths', async () => {
    const res = await fetch(`${base}/nope`);
    assert.equal(res.status, 404);
  });

  it('returns billing JSON at /api/billing', async () => {
    const res = await fetch(`${base}/api/billing`);
    assert.equal(res.status, 200);
    const data = await res.json();
    assert.ok(data.timestamp);
    assert.ok(data.providers);
    assert.ok('spend' in data);
    assert.ok('piSpend' in data);
    for (const p of Object.values(data.providers)) {
      assert.equal(p.detected, false);
    }
  });

  it('serves data/billing.js as generated JS', async () => {
    const res = await fetch(`${base}/data/billing.js`);
    assert.equal(res.status, 200);
    const text = await res.text();
    assert.ok(text.startsWith('// Auto-generated by amster dump'));
    assert.ok(text.includes('window.BILLING = '));
  });

  it('serves src/themes.js as JavaScript', async () => {
    const res = await fetch(`${base}/src/themes.js`);
    assert.equal(res.status, 200);
    const text = await res.text();
    assert.ok(text.includes('AMS_THEMES'));
  });

  it('serves src/providers/catalog.js as JavaScript', async () => {
    const res = await fetch(`${base}/src/providers/catalog.js`);
    assert.equal(res.status, 200);
    const text = await res.text();
    assert.ok(text.includes('AMS_PROVIDERS'));
    assert.ok(text.includes("id: 'xai'"));
  });

  it('rejects path traversal in /src/', async () => {
    const res = await fetch(`${base}/src/%2e%2e/package.json`);
    assert.equal(res.status, 404);
  });
});

describe('server caching', () => {
  it('caches /api/billing within TTL', async () => {
    let calls = 0;
    const countingFetch = async () => {
      calls++;
      return {
        ok: true,
        json: async () => ({ balance_infos: [{ currency: 'CNY', total_balance: '10' }], is_available: true }),
      };
    };
    const env = { DEEPSEEK_API_KEY: 'sk-test' };
    const app = await listen(createApp({ env, fetchFn: countingFetch, loadEnv: false }));
    const base = baseUrl(app);

    await fetch(`${base}/api/billing`);
    await fetch(`${base}/api/billing`);
    assert.equal(calls, 1);

    app.close();
  });

  it('bypasses cache with ?fresh=1', async () => {
    let calls = 0;
    const countingFetch = async () => {
      calls++;
      return {
        ok: true,
        json: async () => ({ balance_infos: [{ currency: 'CNY', total_balance: '10' }], is_available: true }),
      };
    };
    const env = { DEEPSEEK_API_KEY: 'sk-test' };
    const app = await listen(createApp({ env, fetchFn: countingFetch, loadEnv: false }));
    const base = baseUrl(app);

    await fetch(`${base}/api/billing`);
    await fetch(`${base}/api/billing?fresh=1`);
    assert.equal(calls, 2);

    app.close();
  });
});

describe('server credential reload', () => {
  it('detects keys added after startup without a restart', async () => {
    const tmp = mkdtempSync(join(tmpdir(), 'amsterdam-srv-'));
    const hermesDir = join(tmp, '.hermes');
    mkdirSync(hermesDir, { recursive: true });
    const authFile = join(hermesDir, 'auth.json');
    writeFileSync(authFile, JSON.stringify({ credential_pool: {} }));

    const prevHome = process.env.HOME;
    const prevCwd = process.cwd();
    process.env.HOME = tmp;
    process.chdir(tmp);

    let app;
    try {
      app = await listen(createApp({ env: {}, fetchFn: mockFetch({}), loadEnv: true }));
      const base = baseUrl(app);

      const before = await (await fetch(`${base}/api/billing`)).json();
      assert.equal(before.providers.openai.detected, false);

      // Add a key to the Hermes pool after the daemon is already up.
      writeFileSync(authFile, JSON.stringify({
        credential_pool: { openai: [{ source: 'manual', access_token: 'sk-new' }] },
      }));

      const after = await (await fetch(`${base}/api/billing?fresh=1`)).json();
      assert.equal(after.providers.openai.detected, true);
    } finally {
      if (app) app.close();
      process.env.HOME = prevHome;
      process.chdir(prevCwd);
      rmSync(tmp, { recursive: true, force: true });
    }
  });
});
