import { describe, it, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { createApp } from '../src/server.js';
import { openManualStore, closeManualStore } from '../src/manual-credits.js';

function mockFetch(body, status = 200) {
  return async () => ({ ok: status >= 200 && status < 300, status, json: async () => body });
}

async function listen(app) {
  return new Promise((resolve) => {
    const server = app.listen(0, () => resolve(server));
  });
}

function baseUrl(server) {
  const addr = server.address();
  return `http://127.0.0.1:${addr.port}`;
}

// A fresh manual-credit store in a tmp dir, so tests never touch the
// real data/manual-credits.db.
function tmpStore() {
  const dir = mkdtempSync(join(tmpdir(), 'amsterdam-srv-store-'));
  return { store: openManualStore(join(dir, 'manual-credits.db')), dir };
}

describe('server', () => {
  let server;
  let base;
  let storeDir;
  let store;

  before(async () => {
    storeDir = mkdtempSync(join(tmpdir(), 'amsterdam-srv-main-'));
    store = openManualStore(join(storeDir, 'manual-credits.db'));
    server = await listen(createApp({
      env: {
        PI_SESSIONS_DIR: join(storeDir, 'no-sessions'),
        HERMES_STATE_DB: join(storeDir, 'no-state.db'),
        AMSTERDAM_LOCAL_MODELS_DIR: join(storeDir, 'no-models'),
        DSH_SESSIONS_DIR: join(storeDir, 'no-dsh'),
      },
      fetchFn: mockFetch({}),
      loadEnv: false,
      manualStore: store,
    }));
    base = baseUrl(server);
  });

  after(() => {
    server.close();
    closeManualStore(store);
    rmSync(storeDir, { recursive: true, force: true });
  });

  it('serves the billing console at /', async () => {
    const res = await fetch(`${base}/`);
    assert.equal(res.status, 200);
    const text = await res.text();
    assert.ok(text.includes('Amsterdam Console'));
  });

  it('serves the billing console at /index.html and /console', async () => {
    for (const path of ['/index.html', '/console']) {
      const res = await fetch(`${base}${path}`);
      assert.equal(res.status, 200);
      const text = await res.text();
      assert.ok(text.includes('Amsterdam Console'));
    }
  });

  it('returns 404 for unknown paths', async () => {
    const res = await fetch(`${base}/nope`);
    assert.equal(res.status, 404);
  });

  it('returns billing JSON at /api/billing', async () => {
    const res = await fetch(`${base}/api/billing`);
    assert.equal(res.status, 200);
    const data = await res.json();
    assert.ok(data.timestamp);
    assert.ok(data.providers);
    assert.ok('spend' in data);
    assert.ok('piSpend' in data);
    for (const p of Object.values(data.providers)) {
      assert.equal(p.detected, false);
    }
  });

  it('serves data/billing.js as generated JS', async () => {
    const res = await fetch(`${base}/data/billing.js`);
    assert.equal(res.status, 200);
    const text = await res.text();
    assert.ok(text.startsWith('// Auto-generated by amster dump'));
    assert.ok(text.includes('window.BILLING = '));
  });

  it('serves src/themes.js as JavaScript', async () => {
    const res = await fetch(`${base}/src/themes.js`);
    assert.equal(res.status, 200);
    const text = await res.text();
    assert.ok(text.includes('AMS_THEMES'));
  });

  it('serves src/providers/catalog.js as JavaScript', async () => {
    const res = await fetch(`${base}/src/providers/catalog.js`);
    assert.equal(res.status, 200);
    const text = await res.text();
    assert.ok(text.includes('AMS_PROVIDERS'));
    assert.ok(text.includes("id: 'xai'"));
  });

  it('rejects path traversal in /src/', async () => {
    const res = await fetch(`${base}/src/%2e%2e/package.json`);
    assert.equal(res.status, 404);
  });

  it('rejects absolute-path traversal in /src/', async () => {
    const res = await fetch(`${base}/src//etc/passwd.js`);
    assert.equal(res.status, 404);
  });

  it('rejects absolute-path traversal in /demo/', async () => {
    const res = await fetch(`${base}/demo//etc/passwd.js`);
    assert.equal(res.status, 404);
  });

  it('rejects requests with a foreign Host header', async () => {
    // fetch() refuses to override Host, so use raw http to send one.
    const { request } = await import('node:http');
    const status = await new Promise((resolve, reject) => {
      const req = request(
        { host: '127.0.0.1', port: server.address().port, path: '/api/billing', headers: { Host: 'evil-attacker.com' } },
        (res) => {
          res.resume();
          resolve(res.statusCode);
        },
      );
      req.on('error', reject);
      req.end();
    });
    assert.equal(status, 403);
  });

  it('accepts requests with a local Host header', async () => {
    const res = await fetch(`${base}/api/billing`, {
      headers: { Host: 'localhost' },
    });
    assert.equal(res.status, 200);
  });

  it('accepts requests with a Host listed in AMS_HOST', async () => {
    // fetch() refuses to override Host, so use raw http to send one.
    const { request } = await import('node:http');
    const app = await listen(createApp({
      env: { AMS_HOST: 'mini.tail66290a.ts.net,ignored.example' },
      fetchFn: mockFetch({}),
      loadEnv: false,
    }));
    const status = await new Promise((resolve, reject) => {
      const req = request(
        { host: '127.0.0.1', port: app.address().port, path: '/api/billing', headers: { Host: 'mini.tail66290a.ts.net' } },
        (res) => {
          res.resume();
          resolve(res.statusCode);
        },
      );
      req.on('error', reject);
      req.end();
    });
    app.close();
    assert.equal(status, 200);
  });

  it('serves demo/billing.js as the sample fixture', async () => {
    const res = await fetch(`${base}/demo/billing.js`);
    assert.equal(res.status, 200);
    const text = await res.text();
    assert.ok(text.includes('Sample data for demo mode'));
    assert.ok(text.includes('BILLING'));
  });

  it('rejects path traversal in /demo/', async () => {
    const res = await fetch(`${base}/demo/%2e%2e/package.json`);
    assert.equal(res.status, 404);
  });
});

describe('server manual credits', () => {
  let server;
  let base;
  let storeDir;
  let store;

  before(async () => {
    storeDir = mkdtempSync(join(tmpdir(), 'amsterdam-srv-manual-'));
    store = openManualStore(join(storeDir, 'manual-credits.db'));
    server = await listen(createApp({
      env: { PI_SESSIONS_DIR: join(storeDir, 'no-sessions') },
      fetchFn: mockFetch({}),
      loadEnv: false,
      manualStore: store,
    }));
    base = baseUrl(server);
  });

  after(() => {
    server.close();
    closeManualStore(store);
    rmSync(storeDir, { recursive: true, force: true });
  });

  function post(body, extraHeaders = {}) {
    return fetch(`${base}/api/manual-credits`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...extraHeaders },
      body: typeof body === 'string' ? body : JSON.stringify(body),
    });
  }

  it('starts empty', async () => {
    const res = await fetch(`${base}/api/manual-credits`);
    assert.equal(res.status, 200);
    assert.deepEqual(await res.json(), {});
  });

  it('sets, updates, and deletes a credit', async () => {
    let res = await post({ provider: 'pi', amount: 50 });
    assert.equal(res.status, 200);
    assert.deepEqual(await res.json(), { pi: 50 });

    res = await fetch(`${base}/api/manual-credits`);
    assert.equal(res.status, 200);
    assert.deepEqual(await res.json(), { pi: 50 });

    res = await post({ provider: 'pi', amount: 25 });
    assert.deepEqual(await res.json(), { pi: 25 });

    res = await post({ provider: 'anthropic', amount: 10 });
    assert.deepEqual(await res.json(), { pi: 25, anthropic: 10 });

    res = await post({ provider: 'pi', amount: null });
    assert.deepEqual(await res.json(), { anthropic: 10 });

    res = await post({ provider: 'anthropic', amount: null });
    assert.deepEqual(await res.json(), {});
  });

  it('rejects invalid bodies with 400', async () => {
    const cases = [
      ['not json', 'invalid JSON body'],
      ['', 'empty request body'],
      [JSON.stringify([]), 'body must be a JSON object'],
      [JSON.stringify({ provider: 'nope', amount: 5 }), 'unknown provider "nope"'],
      [JSON.stringify({ provider: 'Pi', amount: 5 }), 'unknown provider "Pi"'],
      [JSON.stringify({ provider: 'pi', amount: -5 }), 'amount must be a finite number >= 0 or null'],
      [JSON.stringify({ provider: 'pi', amount: '50' }), 'amount must be a finite number >= 0 or null'],
      [JSON.stringify({ provider: '', amount: 5 }), 'provider must be a non-empty string matching /^[a-z0-9-]+$/i'],
      [JSON.stringify({ provider: 'pi has spaces', amount: 5 }), 'provider must be a non-empty string matching /^[a-z0-9-]+$/i'],
    ];
    for (const [body, error] of cases) {
      const res = await post(body);
      assert.equal(res.status, 400, `body: ${body}`);
      const data = await res.json();
      assert.equal(data.error, error);
    }
  });

  it('rejects methods other than GET and POST', async () => {
    const res = await fetch(`${base}/api/manual-credits`, { method: 'PUT' });
    assert.equal(res.status, 405);
  });

  it('rejects cross-origin POSTs', async () => {
    const res = await post({ provider: 'pi', amount: 5 }, { Origin: 'https://evil.example' });
    assert.equal(res.status, 403);
    const data = await res.json();
    assert.equal(data.error, 'cross-origin request denied');
    // Nothing was written.
    const state = await (await fetch(`${base}/api/manual-credits`)).json();
    assert.deepEqual(state, {});
  });

  it('rejects POSTs with a javascript: origin', async () => {
    const res = await post({ provider: 'pi', amount: 5 }, { Origin: 'javascript:alert(1)' });
    assert.equal(res.status, 403);
  });

  it('accepts same-origin POSTs', async () => {
    const res = await post({ provider: 'pi', amount: 5 }, { Origin: base });
    assert.equal(res.status, 200);
    assert.deepEqual(await res.json(), { pi: 5 });
    // Clean up so other tests start from an empty store.
    await post({ provider: 'pi', amount: null });
  });

  it('rejects an oversized body with 400', async () => {
    const res = await post({ provider: 'pi', amount: 1, pad: 'x'.repeat(2_000_000) });
    assert.equal(res.status, 400);
    const data = await res.json();
    assert.equal(data.error, 'request body too large');
  });
});

describe('server manual credits feed billing', () => {
  it('adds a pi provider with credit minus real spend and invalidates the cache', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'amsterdam-srv-pi-'));
    const sessionsDir = join(dir, 'sessions');
    mkdirSync(sessionsDir, { recursive: true });
    writeFileSync(join(sessionsDir, '2026-08-07T00-00-00-000Z_sess.jsonl'),
      '{"type":"session","version":3,"id":"s1","timestamp":"2026-08-07T00:00:00Z","cwd":"/home/eve/Coding_Projects/amsterdam"}\n' +
      '{"type":"message","id":"m1","timestamp":"2026-08-07T00:01:00Z","message":{"role":"assistant","provider":"deepseek","model":"deepseek-v4-flash","usage":{"input":100,"output":50,"cacheRead":0,"cacheWrite":0,"reasoning":0,"totalTokens":150,"cost":{"total":1.23}},"stopReason":"toolUse"}}\n');
    const store = openManualStore(join(dir, 'manual-credits.db'));
    const app = await listen(createApp({
      env: { PI_SESSIONS_DIR: sessionsDir },
      fetchFn: mockFetch({}),
      loadEnv: false,
      manualStore: store,
    }));
    const base = baseUrl(app);
    try {
      // First call primes the cache: pi is visible (real spend) but
      // has no credit yet.
      const before = await (await fetch(`${base}/api/billing`)).json();
      assert.ok(before.providers.pi);
      assert.equal(before.providers.pi.kind, 'manual');
      assert.equal(before.providers.pi.credit, null);
      assert.equal(before.providers.pi.remaining, null);

      // The POST must invalidate the billing cache.
      const postRes = await fetch(`${base}/api/manual-credits`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ provider: 'pi', amount: 50 }),
      });
      assert.equal(postRes.status, 200);

      const data = await (await fetch(`${base}/api/billing`)).json();
      assert.ok(data.providers.pi);
      assert.equal(data.providers.pi.detected, true);
      assert.equal(data.providers.pi.credit, 50);
      assert.equal(data.providers.pi.spend, 1.23);
      assert.equal(data.providers.pi.remaining, 48.77);

      // Manual credits for catalog providers ride along in the payload.
      await fetch(`${base}/api/manual-credits`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ provider: 'xai', amount: 7 }),
      });
      const fresh = await (await fetch(`${base}/api/billing?fresh=1`)).json();
      assert.equal(fresh.providers.xai.credit, 7);
      assert.equal(fresh.providers.xai.detected, false);
      assert.equal(fresh.providers.pi.remaining, 48.77);

      // Deleting the credit keeps pi (spend still exists) but nulls
      // credit and remaining.
      await fetch(`${base}/api/manual-credits`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ provider: 'pi', amount: null }),
      });
      const after = await (await fetch(`${base}/api/billing?fresh=1`)).json();
      assert.equal(after.providers.pi.credit, null);
      assert.equal(after.providers.pi.remaining, null);
      assert.equal(after.providers.pi.spend, 1.23);
    } finally {
      app.close();
      closeManualStore(store);
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe('server caching', () => {
  it('caches /api/billing within TTL', async () => {
    let calls = 0;
    const countingFetch = async () => {
      calls++;
      return {
        ok: true,
        json: async () => ({ balance_infos: [{ currency: 'CNY', total_balance: '10' }], is_available: true }),
      };
    };
    const env = { DEEPSEEK_API_KEY: 'sk-test' };
    const { store, dir } = tmpStore();
    const app = await listen(createApp({ env, fetchFn: countingFetch, loadEnv: false, manualStore: store }));
    const base = baseUrl(app);

    try {
      await fetch(`${base}/api/billing`);
      await fetch(`${base}/api/billing`);
      assert.equal(calls, 1);
    } finally {
      app.close();
      closeManualStore(store);
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('bypasses cache with ?fresh=1', async () => {
    let calls = 0;
    const countingFetch = async () => {
      calls++;
      return {
        ok: true,
        json: async () => ({ balance_infos: [{ currency: 'CNY', total_balance: '10' }], is_available: true }),
      };
    };
    const env = { DEEPSEEK_API_KEY: 'sk-test' };
    const { store, dir } = tmpStore();
    const app = await listen(createApp({
      env, fetchFn: countingFetch, loadEnv: false, manualStore: store, freshMinIntervalMs: 0,
    }));
    const base = baseUrl(app);

    try {
      await fetch(`${base}/api/billing`);
      await fetch(`${base}/api/billing?fresh=1`);
      assert.equal(calls, 2);
    } finally {
      app.close();
      closeManualStore(store);
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('debounces ?fresh=1 within the min interval', async () => {
    let calls = 0;
    const countingFetch = async () => {
      calls++;
      return {
        ok: true,
        json: async () => ({ balance_infos: [{ currency: 'CNY', total_balance: '10' }], is_available: true }),
      };
    };
    const env = { DEEPSEEK_API_KEY: 'sk-test' };
    const { store, dir } = tmpStore();
    const app = await listen(createApp({
      env, fetchFn: countingFetch, loadEnv: false, manualStore: store, freshMinIntervalMs: 60_000,
    }));
    const base = baseUrl(app);

    try {
      // First request primes the cache; the first fresh always passes
      // (lastForceAt starts at 0); the second fresh must hit the
      // debounce and serve the cache instead of re-fetching.
      await fetch(`${base}/api/billing`);
      await fetch(`${base}/api/billing?fresh=1`);
      await fetch(`${base}/api/billing?fresh=1`);
      assert.equal(calls, 2);
    } finally {
      app.close();
      closeManualStore(store);
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe('server credential reload', () => {
  it('detects keys added after startup without a restart', async () => {
    const tmp = mkdtempSync(join(tmpdir(), 'amsterdam-srv-'));
    const hermesDir = join(tmp, '.hermes');
    mkdirSync(hermesDir, { recursive: true });
    const authFile = join(hermesDir, 'auth.json');
    writeFileSync(authFile, JSON.stringify({ credential_pool: {} }));

    const prevHome = process.env.HOME;
    const prevCwd = process.cwd();
    process.env.HOME = tmp;
    process.chdir(tmp);

    let app;
    const { store, dir: storeDir } = tmpStore();
    try {
      app = await listen(createApp({
        env: { PI_SESSIONS_DIR: join(tmp, 'no-sessions') },
        fetchFn: mockFetch({}),
        loadEnv: true,
        manualStore: store,
      }));
      const base = baseUrl(app);

      const before = await (await fetch(`${base}/api/billing`)).json();
      assert.equal(before.providers.openai.detected, false);

      // Add a key to the Hermes pool after the daemon is already up.
      writeFileSync(authFile, JSON.stringify({
        credential_pool: { openai: [{ source: 'manual', access_token: 'sk-new' }] },
      }));

      const after = await (await fetch(`${base}/api/billing?fresh=1`)).json();
      assert.equal(after.providers.openai.detected, true);
    } finally {
      if (app) app.close();
      closeManualStore(store);
      rmSync(storeDir, { recursive: true, force: true });
      process.env.HOME = prevHome;
      process.chdir(prevCwd);
      rmSync(tmp, { recursive: true, force: true });
    }
  });
});
