export function formatBillingJs(data) {
  const json = JSON.stringify(data, null, 2);
  return `// Auto-generated by amster dump — ${data.timestamp}\nwindow.BILLING = ${json};\n`;
}

export function formatSpendLine(model) {
  const cost = model.costStatus === 'local'
    ? 'free'
    : model.costStatus === 'estimated' && model.estimatedCostUsd != null
      ? `$${model.estimatedCostUsd.toFixed(2)}`
      : 'n/a';
  return `  * ${model.model.padEnd(44)} ${cost}  (${model.sessions} sessions)`;
}

export function formatConsoleLine(id, result) {
  if (!result.detected) return `  · ${pad(id)} not configured`;
  if (result.error) return `  ! ${pad(id)} ${result.error}`;
  if (result.balance != null) return `  * ${pad(id)} ${result.currency} ${result.balance.toFixed(2)} remaining`;
  if (result.usage != null) {
    const limit = result.limit != null ? ` / ${result.limit.toFixed(2)} limit` : ' / no limit';
    return `  * ${pad(id)} $${result.usage.toFixed(2)} used${limit}`;
  }
  if (result.username) return `  * ${pad(id)} ${result.username}`;
  if (result.models != null) return `  * ${pad(id)} ${result.models} models`;
  if (result.verified) return `  * ${pad(id)} key verified`;
  return `  ? ${pad(id)} unknown`;
}

function pad(s) {
  return s.padEnd(14);
}
